---
title: "DNRA data processing and data figures"
author: 
date:
output:
  html_document:
    df_print: paged
---

  

```{r setup, include=F}

# Knitting setup
knitr::opts_chunk$set(echo = T,  warning=F, results="hold")
```

```{r libraries, echo=F, results="hide",message=F}

# ----------Install packages----------

# Install required packages if you don't already have them and load them
packages <- c("extrafont","tidyverse")
if ( length(missing_pkgs <- setdiff(packages, rownames(installed.packages()))) > 0) { 
  message("Installing missing package(s): ", paste(missing_pkgs, collapse = ", "))
  install.packages(missing_pkgs)
}
require(extrafont)
require(tidyverse)

# Install and load the ggbrace package, used to add a bracket to the annotation
# and the ggpubr package, used to combine figures

# Uncomment the following lines to install the packages
# devtools::install_github("nicolash2/ggbrace")
# devtools::install_github("kassambara/ggpubr")

library(ggbrace)
library(ggpubr)
```




```{r graphics, echo=F}

# ----------Set up ggplot theme and create a function----------

# Define the common look of all plots
basic_theme <- theme(
  plot.title = element_text(family="Myriad", margin = margin(0,0,10,0), hjust = 0.5),
  plot.subtitle = element_text(family="Myriad", margin = margin(0,0,10,0), hjust = 0.5),
  axis.title.x = element_text(family="Myriad", size=10, margin = margin(10,0,0,0)),
  axis.title.y = element_text(family="Myriad", size=10, margin = margin(10,40,10,10)),  
  axis.text = element_text(family="Myriad", size=8.5, color = "black"),
  legend.title = element_text(family="Myriad", size=10),
  legend.title.align = 0,
  legend.text = element_text(family="Myriad", size=8.5, vjust = 0.65),
  text = element_text(family="Myriad", size=10),
  panel.background = element_rect(fill = "white", color = "grey20"),
  panel.grid = element_blank()
)


# Function that will allow you to skip labeling every other tick mark,
# thus making major and minor ticks
every_nth <- function(x, nth, empty = TRUE, inverse = FALSE) 
  {
  if (!inverse) {
    if(empty) {
      x[1:nth == 1] <- ""
      x
      } else {
        x[1:nth != 1]
        }
    } else {
      if(empty) {
        x[1:nth != 1] <- ""
        x
        } else {
          x[1:nth == 1]
        }
    }
}


# Font used in the theme above
# This sans font came with Adobe software and I like the way it looks in plot labels. You may want to change this to a font you like and have installed, or just delete all references to family="Myriad" and let R use the default
windowsFonts(Myriad=windowsFont("Myriad Pro"))
```


```{r import}

# ----------Import data and modify it----------

# Set your working directory first or use the R project
# Read in csv, exported out of the Google spreadsheet
DNRA_data <- read.csv("Data/DNRA_data_Fig3_Fig4.csv", 
                      comment.char="#", stringsAsFactors=TRUE,
                      na.strings = c("", "NA"),
                      
                      # Set encoding so accented characters show up correctly
                      encoding = "UTF-8")

# Modify the dataset
DNRA_data <- DNRA_data %>%
  mutate(
    Name = str_c(str_replace_na(Year, "NA"),
                 str_replace_na(State_or_province, "NA"), 
                 Country, 
                 Ecosystem_type,
                 sep = "_"),
    Name = str_remove_all(Name, "_NA"),
    State_or_province = str_replace(State_or_province, "_", " "),
    Country = str_replace(Country, "_", " "),
    Ecosystem_type = str_to_sentence(Ecosystem_type),
    
    # Set an order for ecosystem types we can use in plots
    Ecosystem_order = case_when(str_detect(Ecosystem_type, "burgin") ~ "01",
                                Ecosystem_type == "Wetland" ~ "05",
                                Ecosystem_type == "3 wetlands" ~ "06",
                                Ecosystem_type == "Constructed_wetland" ~ "07",
                                str_detect(Ecosystem_type, "ake") ~ "02",
                                Ecosystem_type == "Reservoir" ~ "03",
                                str_detect(Ecosystem_type, "tream") ~ "04",
                                str_detect(Ecosystem_type, "roundwater") ~ "08",
                                TRUE ~ "NA"),
    Ecosystem_order = na_if(Ecosystem_order, "NA"),
    Ecosystem_order = as.numeric(Ecosystem_order),
    
    # Remove and replace strings in variables; the first removes "_burgin-2007"
    Ecosystem_type = str_remove(Ecosystem_type, "_b.*"),
    Ecosystem_type = str_replace_all(Ecosystem_type, "_", " "),
    Ecosystem_type = str_replace_all(Ecosystem_type, "-", " "),
    Subrep = str_replace_all(Subrep, "_", " "),
    
    # Make sure all measurement quality values are in the same case,
    # then convert them to new values
    Measurement_quality = str_to_lower(Measurement_quality),
    Measurement_quality = case_when(Measurement_quality == "high" ~ "Isotopic",
                                    Measurement_quality == "low" ~ "Other",
                                    TRUE ~ "NA"),
    
    # Create a label to use in the figures for each entry
    Label = str_c(
      Ecosystem_type,
      # Change all NA values to text that says NA
      str_replace_na(Subrep, "NA"), 
      str_replace_na(State_or_province, "NA"),
      Country,
      sep = ", "),
    # Then remove the NAs from the labels
    Label = str_remove_all(Label, ", NA")
  ) %>% 
  
  # Order by ecosystem type and add ordering numbers to name and label,
  # keeping the original order within ecosystem types
  arrange(Ecosystem_order) %>% 
  mutate(
    Rownum = str_pad(row.names(DNRA_data), width = 3, pad = "0"),
    Name = str_c(Rownum, Name, sep = "_"),
    Label = str_c(Rownum, Label, sep = "_"),
    
    # Convert DNRA rates to all have the units, all areal rates to umol N m-2 h-1
    # and all mass units to nmol N g-1 h-1
    DNRA_rate_min = case_when(
      Units_DNRA_rate == "umol_N_m2_h-1" ~ DNRA_rate_min,
      Units_DNRA_rate == "mg_N_m-2_d-1" ~ DNRA_rate_min * 10^6 / (24 * 1000 * 14.0067),
      Units_DNRA_rate == "nmol_N_g-1_h-1" ~ DNRA_rate_min,
      Units_DNRA_rate == "ug_N_kg-1_d-1" ~ DNRA_rate_min * 10^9 / (1000 * 24 * 10^6 * 14.0067),
      Units_DNRA_rate == "ug_N_g-1_d-1" ~ DNRA_rate_min * 10^9 / (24 * 10^6 * 14.0067),
      Units_DNRA_rate == "ug_N_g-1_h-1" ~ DNRA_rate_min * 10^9 / (10^6 * 14.0067),
      Units_DNRA_rate == "umol_N_kg-1_h-1" ~ DNRA_rate_min,
      TRUE ~ DNRA_rate_min
    ),
    
    DNRA_rate_max = case_when(
      Units_DNRA_rate == "umol_N_m2_h-1" ~ DNRA_rate_max,
      Units_DNRA_rate == "mg_N_m-2_d-1" ~ DNRA_rate_max * 10^6 / (24 * 1000 * 14.0067),
      Units_DNRA_rate == "nmol_N_g-1_h-1" ~ DNRA_rate_max,
      Units_DNRA_rate == "ug_N_kg-1_d-1" ~ DNRA_rate_max * 10^9 / (1000 * 24 * 10^6 * 14.0067),
      Units_DNRA_rate == "ug_N_g-1_d-1" ~ DNRA_rate_max * 10^9 / (24 * 10^6 * 14.0067),
      Units_DNRA_rate == "ug_N_g-1_h-1" ~ DNRA_rate_max * 10^9 / (10^6 * 14.0067),
      Units_DNRA_rate == "umol_N_kg-1_h-1" ~ DNRA_rate_max,
      TRUE ~ DNRA_rate_max
    ),
    
    DNRA_rate_mean = case_when(
      Units_DNRA_rate == "umol_N_m2_h-1" ~ DNRA_rate_mean,
      Units_DNRA_rate == "mg_N_m-2_d-1" ~ DNRA_rate_mean * 10^6 / (24 * 1000 * 14.0067),
      Units_DNRA_rate == "nmol_N_g-1_h-1" ~ DNRA_rate_mean,
      Units_DNRA_rate == "ug_N_kg-1_d-1" ~ DNRA_rate_mean * 10^9 / (1000 * 24 * 10^6 * 14.0067),
      Units_DNRA_rate == "ug_N_g-1_d-1" ~ DNRA_rate_mean * 10^9 / (24 * 10^6 * 14.0067),
      Units_DNRA_rate == "ug_N_g-1_h-1" ~ DNRA_rate_mean * 10^9 / (10^6 * 14.0067),
      Units_DNRA_rate == "umol_N_kg-1_h-1" ~ DNRA_rate_mean,
      TRUE ~ DNRA_rate_mean
    ),
    
    DNRA_rate_SE = case_when(
      Units_DNRA_rate == "umol_N_m2_h-1" ~ DNRA_rate_SE,
      Units_DNRA_rate == "mg_N_m-2_d-1" ~ DNRA_rate_SE * 10^6 / (24 * 1000 * 14.0067),
      Units_DNRA_rate == "nmol_N_g-1_h-1" ~ DNRA_rate_SE,
      Units_DNRA_rate == "ug_N_kg-1_d-1" ~ DNRA_rate_SE * 10^9 / (1000 * 24 * 10^6 * 14.0067),
      Units_DNRA_rate == "ug_N_g-1_d-1" ~ DNRA_rate_SE * 10^9 / (24 * 10^6 * 14.0067),
      Units_DNRA_rate == "ug_N_g-1_h-1" ~ DNRA_rate_SE * 10^9 / (10^6 * 14.0067),
      Units_DNRA_rate == "umol_N_kg-1_h-1" ~ DNRA_rate_SE,
      TRUE ~ DNRA_rate_SE
    ),
    
  )

# Export a csv, useful for data exploration in Excel
write.csv(DNRA_data, "Output/DNRA_data_transformed.csv", row.names = FALSE)

```


```{r fig 3 areal, fig.width=3, fig.height=4, out.width="100%", dpi=300}

# ----------Create Figure 3a, areal DNRA rates compared----------

# First make figure for areal rates
DNRA_data_fig_areal <- DNRA_data %>% 
  filter(Type_units == "areal")

fig_areal <- ggplot(DNRA_data_fig_areal, aes(x = Label)) +
  geom_segment(aes(x = Label,
                   xend = Label,
                   y = DNRA_rate_min,
                   yend = DNRA_rate_max,
                   color = Measurement_quality),
               size = 5) +
  geom_point(aes(y = DNRA_rate_mean,
                 color = Measurement_quality),
             size = 3) +
  scale_color_brewer(palette = "Set2", direction = 1) +
  geom_errorbar(aes(x = Label,
    ymin = DNRA_rate_mean - DNRA_rate_SE,
    ymax = DNRA_rate_mean + DNRA_rate_SE),
    width=0.4, colour="black", alpha=0.7, size=0.5) +
  scale_x_discrete(labels = str_remove(DNRA_data_fig_areal$Label, "\\d\\d\\d_")) +
  scale_y_continuous(expand = expansion(mult = c(0, .05))) +
  coord_cartesian(clip = "off") +
  labs(y = expression(mu*"mol N m"^"-2"*" h"^"-1"),
       x = "",
       color = "Measurement method") +
  basic_theme +
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1),
        axis.text.y = element_text(vjust = 0.35),
        axis.title.y = element_text(family="Myriad", size=12,
                                    margin = margin(l = 0.7, r = 0.48, unit = "in")),
        plot.margin = margin(0, 0, 0, 0),
        panel.border = element_rect(color = "black", size = 0.5, fill = NA),
        legend.position = "none",
        legend.background = element_rect(fill = "white", color = "grey30", size = 0.05),
        legend.box.margin = margin(2, 2, 2, 5),
        legend.key = element_rect(fill = "white")
  )

fig_areal

ggsave(file="Output/Fig3_areal.png", fig_areal, width=3, height=4, units="in", dpi=300)
```


```{r fig 3 mass, fig.width=6.5, fig.height=4.33, out.width="100%", dpi=300}

# ----------Create Figure 3b, DNRA rates by mass compared----------

# First make figure for mass rates
DNRA_data_fig_mass <- DNRA_data %>% 
  filter(Type_units == "mass",
         Fig_3_rates == "yes")

fig_mass <- ggplot(DNRA_data_fig_mass, aes(x = Label)) +
  geom_segment(aes(x = Label,
                   xend = Label,
                   y = DNRA_rate_min,
                   yend = DNRA_rate_max,
                   color = Measurement_quality),
               size = 5) +
  geom_point(aes(y = DNRA_rate_mean,
                 color = Measurement_quality),
             size = 3) +
  scale_color_brewer(palette = "Set2", direction = 1) +
  geom_errorbar(aes(x = Label,
    ymin = DNRA_rate_mean - DNRA_rate_SE,
    ymax = DNRA_rate_mean + DNRA_rate_SE),
    width=0.4, colour="black", alpha=0.7, size=0.5) +
  scale_x_discrete(labels = str_remove(DNRA_data_fig_mass$Label, "\\d\\d\\d_")) +
  scale_y_continuous(expand = expansion(mult = c(0, .05))) +
  coord_cartesian(clip = "off") +
  labs(y = expression("nmol N g"^"-1"*" h"^"-1"),
       x = "",
       color = "Measurement method") +
  basic_theme +
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1),
        axis.text.y = element_text(vjust = 0.35),
        axis.title.y = element_text(family="Myriad", size=12, margin = margin(l = 0.7, r = 0.4, unit = "in")),
        plot.margin = margin(0, 0, 0, 0),
        panel.border = element_rect(color = "black", size = 0.5, fill = NA),
        legend.position = c(0.15, 0.77),
        legend.background = element_rect(fill = "white", color = "grey30", size = 0.05),
        legend.box.margin = margin(2, 2, 2, 5),
        legend.key = element_rect(fill = "white")
  )

fig_mass

ggsave(file="Output/Fig3_mass.png", fig_mass, width=6.5, height=4.33, units="in", dpi=300)
```


```{r fig 3 combine, fig.width=6.5, fig.height=8.33, out.width="100%", dpi=300}

# ----------Combine Fig 3 a and b----------

fig_3a <- fig_areal
fig_3b <- fig_mass + theme(legend.position = c(0.8, 1.895))

fig3 <- ggarrange(ggarrange(fig_3a,
                    ncol = 2,
                    widths = c(3, 3.5)),
          fig_3b,
          labels = c("a", "b"),
          nrow = 2,
          heights = c(3, 4.33)
          )

fig3

ggsave(file="Output/Fig3_combined.png", fig3, width=6.5, height=7.33, units="in", dpi=300)

```



```{r fig 4, fig.width=6.5, fig.height=5.2, out.width="100%", dpi=300}

# ----------Create Figure 4, DNRA as percent of total dissim reduction----------

DNRA_data_fig4 <- DNRA_data %>% 
  filter(Fig_4_percent == "yes")

fig4 <- ggplot(DNRA_data_fig4, aes(x = Label)) +
  geom_segment(aes(x = Label,
                   xend = Label,
                   y = DNRA_percent_removal_min,
                   yend = DNRA_percent_removal_max,
                   color = Measurement_quality),
               size = 5) +
  geom_point(aes(y = DNRA_percent_removal_mean,
                 color = Measurement_quality),
             size = 3) +
  scale_color_brewer(palette = "Set2", direction = 1) +
  geom_errorbar(aes(x = Label,
    ymin = DNRA_percent_removal_mean - DNRA_percent_removal_SE,
    ymax = DNRA_percent_removal_mean + DNRA_percent_removal_SE),
    width=0.4, colour="black", alpha=0.7, size=0.5) +
  scale_x_discrete(labels = str_remove(DNRA_data_fig4$Label, "\\d\\d\\d_")) +
  scale_y_continuous(breaks = seq(0, 110, by = 10),
                     labels = every_nth(seq(0, 110, by = 10), 2, inverse = TRUE),
                     expand = expansion(mult = c(0, .05))) +
  coord_cartesian(clip = "off") +
  ylab("% DNRA") +
  xlab("") +
  labs(color = "Measurement method") +
  basic_theme +
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1),
        axis.text.y = element_text(vjust = 0.35),
        axis.title.y = element_text(margin = margin(l = 0.16, r = 0.4, unit = "in")),
        plot.margin = margin(0, 0, 0, 0),
        panel.border = element_rect(color = "black", size = 0.5, fill = NA),
        legend.position = c(0.35, 0.8),
        legend.background = element_rect(fill = "white", color = "grey30", size = 0.05),
        legend.box.margin = margin(2, 2, 2, 5),
        legend.key = element_rect(fill = "white")
  )


fig4 +
  geom_brace(aes(c(0.6, 4.4), c(60, 65)),
                  inherit.data = FALSE,
                  color = "blue",
                  size = 0.3) +
  geom_text(aes(x = 2.5, y = 78, label = "Included in\nBurgin and Hamilton\n(2007)"),
           family = "Myriad", size = 8/.pt, alpha = 0.08, color = "blue")

ggsave(file = "Output/Fig4.png", 
       plot = fig4 + 
         geom_brace(aes(c(0.6, 4.4), c(60, 65)),
                    inherit.data = FALSE,
                    color = "blue",
                    size = 0.3) +
         geom_text(aes(x = 2.5, y = 78, 
                       label = "Included in\nBurgin and Hamilton\n(2007)"),
                   family = "Myriad", size = 8/.pt, 
                   alpha = 0.08, color = "blue"),
       width=6.5, height=5.2, units="in", dpi=300)
```


```{r fig 4 flipped, fig.width=7.5, fig.height=5, out.width="100%", dpi=300}

# ----------Flip Fig 4 to have horizontal bars----------

DNRA_data <- DNRA_data %>% 
  mutate(Label_flip = str_c(Rownum, "_", Label))

fig4_flipped <- ggplot(DNRA_data, aes(x = Name)) +
  geom_segment(aes(x = Name,
                   xend = Name,
                   y = DNRA_percent_removal_min,
                   yend = DNRA_percent_removal_max,
                   color = Measurement_quality),
               size = 5) +
  geom_point(aes(y = DNRA_percent_removal_mean,
                 color = Measurement_quality),
             size = 3) +
  scale_color_brewer(palette = "Set2", direction = 1) +
  geom_errorbar(aes(x = Name,
    ymin = DNRA_percent_removal_mean - DNRA_percent_removal_SE,
    ymax = DNRA_percent_removal_mean + DNRA_percent_removal_SE),
    width=0.4, colour="black", alpha=0.7, size=0.5) +
  scale_x_discrete(limits = rev(levels(as.factor(DNRA_data$Name))),
                   labels = str_remove(rev(levels(as.factor(DNRA_data$Label_flip))),
                                       "\\d\\d_")) +
  scale_y_continuous(breaks = seq(0, 110, by = 10),
                     labels = every_nth(seq(0, 110, by = 10), 2, inverse = TRUE),
                     expand = expansion(mult = c(0, .05))) +
  ylab("% DNRA") +
  xlab("") +
  labs(color = "Measurement method") +
  coord_flip(clip = "off") +
  basic_theme +
  theme(axis.text.y = element_text(hjust = 1, vjust = 0.5),
        axis.text.x = element_text(vjust = 0.35),
        axis.title.y = element_blank(),
        plot.margin = margin(0, 0, 0, 0),
        panel.border = element_rect(color = "black", size = 0.5, fill = NA),
        legend.position = c(0.7, 0.6),
        legend.background = element_rect(fill = "white", color = "grey30", size = 0.05),
        legend.box.margin = margin(2, 2, 2, 5),
        legend.key = element_rect(fill = "white")
  )

fig4_flipped + 
  geom_brace(aes(c(15.6, 18.4), c(60, 65)),
                  inherit.data = FALSE,
                  color = "blue",
                  size = 0.3) +
  geom_text(aes(x = 17, y = 78, label = "Included in\nBurgin and\nHamilton\n2007"),
           family = "Myriad", size = 8/.pt, alpha = 0.08, color = "blue")

ggsave(file="Output/Fig4_flipped.png", plot = fig4_flipped + 
  geom_brace(aes(c(15.6, 18.4), c(60, 65)),
                  inherit.data = FALSE,
                  color = "blue",
                  size = 0.3) +
  geom_text(aes(x = 17, y = 78, label = "Included in\nBurgin and\nHamilton\n2007"),
           family = "Myriad", size = 8/.pt, alpha = 0.08, color = "blue"),
       width=7.5, height=5, units="in", dpi=300)
```




























